name: healthcare
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management
  get: 4.6.6

  # svg files
  flutter_svg: ^2.0.10+1

  # class equatable
  equatable: ^2.0.5

  # dependencies injection
  get_it: ^7.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/breast_checkup/